---
on:
  workflow_call:

env:
  PACKER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  # PACKER_LOG: "1"

jobs:
  x86_64:
    runs-on: [self-hosted, X64, vmware]
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-11
          - windows-2016
          - windows-2019
          - windows-2022
          - windows-2025
        provider:
          - vmware-iso
    steps:
      - name: Checkout
        uses: actions/checkout@main
#      - name: Setup Packer
#        if: steps.verify-changed-files.outputs.files_changed == 'true'
#        uses: hashicorp/setup-packer@main
#        with:
#          version: latest
      - name: Bento build
        run: |
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm --vars 'ssh_timeout=30m' os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-x86_64.pkrvars.hcl"
          ls -alh builds/
          cat builds/${{ matrix.os }}*-x86_64._metadata.json
      - name: Remove VM in case of canceled job
        if: cancelled()
        run: |
          VM="$(prlctl list -a | grep ${{ matrix.os }} | cut -d " " -f 1)"
          echo Powering off and deleting any existing VMs named ${{ matrix.os }}*-x86_64
          prlctl stop "$VM" --kill 2> /dev/null
          sleep 1
          prlctl delete "$VM" 2> /dev/null
          sleep 2
      - name: Bento Test
        run: |
          eval "$(chef shell-init bash)"
          bento test
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-parallels-x86_64"
          path: |
            builds/*.box
            builds/*.json
          overwrite: true
          retention-days: 10
          compression-level: 0 # no compression
