---
on:
  workflow_call:

env:
  PACKER_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  PACKER_LOG: "1"

jobs:
  aarch64:
    runs-on: [self-hosted, ARM64, qemu]
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-11
        provider:
          - qemu
    steps:
      - name: Checkout
        uses: actions/checkout@main
#      - name: Setup Packer
#        if: steps.verify-changed-files.outputs.files_changed == 'true'
#        uses: hashicorp/setup-packer@main
#        with:
#          version: latest
      - name: Bento build
        run: |
          eval "$(chef shell-init bash)"
          bento build -o ${{ matrix.provider }}.vm --vars 'ssh_timeout=30m' --vars "qemu_accelerator=hvf" os_pkrvars/$(echo ${{ matrix.os }} | cut -d "-" -f 1)/"${{ matrix.os }}-aarch64.pkrvars.hcl"
          ls -alh builds/
          cat builds/${{ matrix.os }}*-aarch64._metadata.json
      - name: Bento Test
        run: |
          eval "$(chef shell-init bash)"
          bento test libvirt
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ matrix.os }}-qemu-aarch64"
          path: |
            builds/*.box
            builds/*.json
          overwrite: true
          retention-days: 10
          compression-level: 0 # no compression
